### ISSUE TITLE
Feature request: Select/highlight duplicates only in selection

### ISSUE THREAD

**Issue by radek-vizlib** [LordBrom/HighlightDuplicates-vscode#1]
I have large files and I want to select/highlight duplicates only in my selection.
e.g. for a case like this

  A
  B
  C
```
// selection start
X
C
B
C
H
// election end
```
  X
  Y
  Z
  
  I want to select/highlight only C (because it is duplicate in the selection) and I don't want to select B or X

**Comment by LordBrom** [comment]
Hello, Sorry for the slow reply. I will make this update and there should be a new version of the plugin out in a few days. 

Thank you or using the plugin!

**Comment by LordBrom** [comment]
I've deployed a new version with these updates. I'm going to close this ticket, but feel free to open a new one for anything else. Thanks again.
